[package]
name = "libtest-sys"
version = "0.1.0"
authors = ["vagrant"]
edition = "2018"
links = "test"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.51"
cc = "1.0"
pkg-config = "0.3"

