image: rust

stages:
  - test
  - publish

before_script:
  - apt-get update
  - apt-get install -y libclang-dev autoconf automake libtool
  # - export CPATH=/usr/lib/llvm-3.9/lib/clang/3.9.1/include/

test:
  stage: test
  script:
  - cargo test

publish:
  stage: publish
  script:
  - cargo login $CARGO_TOKEN
  - cargo package
  - cargo publish
  only:
  - tags
