[package]
name = "sqlite"
version = "0.1.0"
authors = ["Enrico Ghirardi <enrico.ghirardi@decentriq.ch>"]
edition = "2018"

[dependencies]
time = "0.1.42"
rs-libc-decentriq = { path = "../.." }
rs-libc = "0.2.0"

[dependencies.rusqlite]
features = ["bundled"]
version = "0.21.0"
